on: push

defaults:
  run:
    working-directory: application/ui

jobs:
  test:
    name: Test UI
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2
      - name: using node.js to build project
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Run Tests
        run: |
          yarn install
          yarn test
          yarn build
